package diegoandino_lab5p2;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        setVisible(true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        actu_tree();
    }
    ArrayList<Personajes> personajes = new ArrayList();
    Random aleatorio = new Random();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jF_Crear = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTF_Nombre = new javax.swing.JTextField();
        jTF_Poder = new javax.swing.JTextField();
        jTF_Debilidad = new javax.swing.JTextField();
        jS_Fisica = new javax.swing.JSpinner();
        jS_Mental = new javax.swing.JSpinner();
        jS_Fuerza = new javax.swing.JSpinner();
        jS_HP = new javax.swing.JSpinner();
        jRB_Marvel = new javax.swing.JRadioButton();
        jRB_CapCom = new javax.swing.JRadioButton();
        jRB_DC = new javax.swing.JRadioButton();
        jRB_MK = new javax.swing.JRadioButton();
        jB_crear1 = new javax.swing.JButton();
        jB_EVolver = new javax.swing.JButton();
        jF_Listar = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jT_Personajes = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jB_Regreso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jL_Personajes = new javax.swing.JList<>();
        jF_Battle = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        CB_Jug1 = new javax.swing.JComboBox<>();
        CB_Jug2 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jL_Jug1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jL_Jug2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        AreaBattle = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jBT_Fis = new javax.swing.JButton();
        jBT_Men = new javax.swing.JButton();
        jBT_Res = new javax.swing.JButton();
        Salida = new javax.swing.JButton();
        bG_Universo = new javax.swing.ButtonGroup();
        PopMenu = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jB_Listar = new javax.swing.JButton();
        jB_Battle = new javax.swing.JButton();
        jB_Crear2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre: ");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Poder:");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Universo:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Debilidad:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Agilidada fisica:");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Agilidad Mental:");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Fuerza:");

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("HP:");

        jTF_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_NombreActionPerformed(evt);
            }
        });

        jTF_Poder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_PoderActionPerformed(evt);
            }
        });

        bG_Universo.add(jRB_Marvel);
        jRB_Marvel.setForeground(new java.awt.Color(0, 0, 0));
        jRB_Marvel.setText("Marvel");
        jRB_Marvel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_MarvelActionPerformed(evt);
            }
        });

        bG_Universo.add(jRB_CapCom);
        jRB_CapCom.setForeground(new java.awt.Color(0, 0, 0));
        jRB_CapCom.setText("CapCom");
        jRB_CapCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_CapComActionPerformed(evt);
            }
        });

        bG_Universo.add(jRB_DC);
        jRB_DC.setForeground(new java.awt.Color(0, 0, 0));
        jRB_DC.setText("DC");
        jRB_DC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_DCActionPerformed(evt);
            }
        });

        bG_Universo.add(jRB_MK);
        jRB_MK.setForeground(new java.awt.Color(0, 0, 0));
        jRB_MK.setText("MK");
        jRB_MK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_MKActionPerformed(evt);
            }
        });

        jB_crear1.setBackground(new java.awt.Color(102, 102, 102));
        jB_crear1.setForeground(new java.awt.Color(255, 255, 255));
        jB_crear1.setText("Crear");
        jB_crear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_crear1ActionPerformed(evt);
            }
        });

        jB_EVolver.setBackground(new java.awt.Color(102, 102, 102));
        jB_EVolver.setForeground(new java.awt.Color(255, 255, 255));
        jB_EVolver.setText("Volver");
        jB_EVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTF_Poder, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jS_Fisica))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel8)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel9))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jS_Mental, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jS_Fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jS_HP, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jTF_Debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jRB_Marvel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_DC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_CapCom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRB_MK)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB_crear1)
                .addGap(116, 116, 116)
                .addComponent(jB_EVolver)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTF_Poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTF_Debilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRB_Marvel)
                        .addComponent(jRB_CapCom)
                        .addComponent(jRB_DC)
                        .addComponent(jRB_MK)))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jS_Mental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_Fuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_HP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jS_Fisica, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_EVolver)
                    .addComponent(jB_crear1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jF_CrearLayout = new javax.swing.GroupLayout(jF_Crear.getContentPane());
        jF_Crear.getContentPane().setLayout(jF_CrearLayout);
        jF_CrearLayout.setHorizontalGroup(
            jF_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jF_CrearLayout.setVerticalGroup(
            jF_CrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Personajes");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("DC");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Marvel");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Mortal Kombat");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Capcom");
        treeNode1.add(treeNode2);
        jT_Personajes.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jT_Personajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_PersonajesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jT_Personajes);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("LISTAJE DE PERSONAJES");

        jB_Regreso.setBackground(new java.awt.Color(102, 102, 102));
        jB_Regreso.setForeground(new java.awt.Color(255, 255, 255));
        jB_Regreso.setText("Regreso");
        jB_Regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_RegresoActionPerformed(evt);
            }
        });

        jL_Personajes.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jL_Personajes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jB_Regreso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(jB_Regreso, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout jF_ListarLayout = new javax.swing.GroupLayout(jF_Listar.getContentPane());
        jF_Listar.getContentPane().setLayout(jF_ListarLayout);
        jF_ListarLayout.setHorizontalGroup(
            jF_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jF_ListarLayout.setVerticalGroup(
            jF_ListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 102, 102));

        CB_Jug1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Mortal Kombat", "Capcom" }));
        CB_Jug1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_Jug1ItemStateChanged(evt);
            }
        });

        CB_Jug2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DC", "Marvel", "Mortal Kombat", "Capcom" }));
        CB_Jug2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_Jug2ItemStateChanged(evt);
            }
        });
        CB_Jug2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_Jug2ActionPerformed(evt);
            }
        });

        jL_Jug1.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jL_Jug1);

        jL_Jug2.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jL_Jug2);

        AreaBattle.setColumns(20);
        AreaBattle.setRows(5);
        jScrollPane5.setViewportView(AreaBattle);

        jLabel11.setBackground(new java.awt.Color(51, 51, 51));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("VS");

        jBT_Fis.setText("Ataque Fisico");
        jBT_Fis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBT_FisMouseClicked(evt);
            }
        });

        jBT_Men.setText("Ataque Mental");
        jBT_Men.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_MenActionPerformed(evt);
            }
        });

        jBT_Res.setText("Resistencia");
        jBT_Res.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_ResActionPerformed(evt);
            }
        });

        Salida.setText("Salida");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Jug1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CB_Jug2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jBT_Fis)
                                .addGap(47, 47, 47)
                                .addComponent(jBT_Men)
                                .addGap(42, 42, 42)
                                .addComponent(jBT_Res))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(Salida)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CB_Jug1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CB_Jug2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBT_Fis)
                    .addComponent(jBT_Men)
                    .addComponent(jBT_Res))
                .addGap(18, 18, 18)
                .addComponent(Salida)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jF_BattleLayout = new javax.swing.GroupLayout(jF_Battle.getContentPane());
        jF_Battle.getContentPane().setLayout(jF_BattleLayout);
        jF_BattleLayout.setHorizontalGroup(
            jF_BattleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jF_BattleLayout.setVerticalGroup(
            jF_BattleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Eliminar.setText("jMenuItem1");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        PopMenu.add(Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jB_Listar.setBackground(new java.awt.Color(51, 51, 51));
        jB_Listar.setForeground(new java.awt.Color(255, 255, 255));
        jB_Listar.setText("LISTAR");
        jB_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ListarActionPerformed(evt);
            }
        });

        jB_Battle.setBackground(new java.awt.Color(51, 51, 51));
        jB_Battle.setForeground(new java.awt.Color(255, 255, 255));
        jB_Battle.setText("BATTLE");
        jB_Battle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_BattleActionPerformed(evt);
            }
        });

        jB_Crear2.setBackground(new java.awt.Color(51, 51, 51));
        jB_Crear2.setForeground(new java.awt.Color(255, 255, 255));
        jB_Crear2.setText("CREAR");
        jB_Crear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_Crear2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("//---------GAME START---------//");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jB_Crear2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jB_Battle, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(jB_Listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jB_Crear2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jB_Listar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jB_Battle, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ListarActionPerformed
        //VENTANA LISTAR
        jF_Listar.pack();
        jF_Listar.setLocationRelativeTo(this);
        this.setVisible(false);
        jF_Listar.setVisible(true);

    }//GEN-LAST:event_jB_ListarActionPerformed

    private void jB_BattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_BattleActionPerformed
        //VENTANA LUCHA
        jF_Battle.pack();
        jF_Battle.setLocationRelativeTo(this);
        this.setVisible(false);
        jF_Battle.setVisible(true);


    }//GEN-LAST:event_jB_BattleActionPerformed

    private void jB_Crear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_Crear2ActionPerformed
        //VENTANA CREAR
        jF_Crear.pack();
        jF_Crear.setLocationRelativeTo(this);
        this.setVisible(false);
        jF_Crear.setVisible(true);


    }//GEN-LAST:event_jB_Crear2ActionPerformed

    private void jTF_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_NombreActionPerformed

    private void jTF_PoderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_PoderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_PoderActionPerformed

    private void jRB_MarvelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_MarvelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_MarvelActionPerformed

    private void jRB_CapComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_CapComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_CapComActionPerformed

    private void jRB_DCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_DCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_DCActionPerformed

    private void jRB_MKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_MKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRB_MKActionPerformed

    private void jB_crear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_crear1ActionPerformed
        //Crear
        String uni = "";
        if (jRB_Marvel.isSelected()) {
            uni = "Marvel";
        } else if (jRB_DC.isSelected()) {
            uni = "DC";
        } else if (jRB_CapCom.isSelected()) {
            uni = "Capcom";
        } else if (jRB_MK.isSelected()) {
            uni = "MK";
        }
        String Nombre = jTF_Nombre.getText();
        String Poder = jTF_Poder.getText();
        String Debilidad = jTF_Debilidad.getText();

        Personajes.add(new Personajes(Nombre, Poder, Debilidad, uni, (int) jS_Fuerza.getValue(), (int) jS_Fisica.getValue(), (int) jS_Mental.getValue(), (int) jS_HP.getValue()));
        actu_tree();

    }//GEN-LAST:event_jB_crear1ActionPerformed

    private void jB_EVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EVolverActionPerformed
        //Volver
        jF_Crear.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jB_EVolverActionPerformed

    private void jB_RegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_RegresoActionPerformed
        //Regreso
        jF_Listar.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jB_RegresoActionPerformed

    private void jT_PersonajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_PersonajesMouseClicked
        // OPCION MENU
        if (evt.isMetaDown()) {
            int row = jT_Personajes.getClosestRowForLocation(evt.getX(), evt.getY());
            jT_Personajes.setSelectionRow(row);
            nodSel = (DefaultMutableTreeNode) jT_Personajes.getSelectionPath().getLastPathComponent();
            DefaultListModel modelo = new DefaultListModel();
            if (nodSel.toString().equals("DC") || nodSel.getUserObject().equals("Marvel") || nodSel.getUserObject().equals("Capcom") || nodSel.getUserObject().equals("MortalKombat")) {
              

                for (Personajes p : personajes) {
                    if (p.getUniverso().equals(nodSel.toString())) {
                        modelo.addElement(p);
                    }
                }

            } else {
                PopMenu.show(evt.getComponent(), evt.getX(), evt.getY());

                modelo.addElement(nodSel.toString());

            }
            jL_Personajes.setModel(modelo);
        }

    }//GEN-LAST:event_jT_PersonajesMouseClicked

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        int response = JOptionPane.showConfirmDialog(
                this,"Seguro de Eliminar?","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {DefaultTreeModel m = (DefaultTreeModel) jT_Personajes.getModel();
            m.removeNodeFromParent(nodSel);
            personajes.remove((Personajes) nodSel.getUserObject());
            m.reload();
            jL_Personajes.setModel(new DefaultListModel());
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void CB_Jug1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_Jug1ItemStateChanged
        jL_Jug1.setModel(Listar(CB_Jug1.getSelectedItem().toString()));
    }//GEN-LAST:event_CB_Jug1ItemStateChanged

    private void CB_Jug2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_Jug2ItemStateChanged
        jL_Jug2.setModel(Listar(CB_Jug2.getSelectedItem().toString()));
    }//GEN-LAST:event_CB_Jug2ItemStateChanged

    private void CB_Jug2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_Jug2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_Jug2ActionPerformed

    private void jBT_FisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBT_FisMouseClicked
        Personajes jugador1 = (Personajes) CB_Jug1.getSelectedItem();
        Personajes jugador2 = (Personajes) CB_Jug2.getSelectedItem();

        double dan = 0.33/1;
        int chance = aleatorio.nextInt(8);
        int vidAct1 = jugador1.getHp();
        int vidAct2 = jugador2.getHp();
        if (chance == 1) {
            jugador1.setHp((int) (vidAct1 + 0.08));
        }

        AreaBattle.setText("Jugador 1 uso ataque fisico..."
        );
    }//GEN-LAST:event_jBT_FisMouseClicked

    private void jBT_MenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_MenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT_MenActionPerformed

    private void jBT_ResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_ResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT_ResActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        // Salir
        jF_Battle.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_SalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    public void actu_tree() {

        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Personajes");

        DefaultMutableTreeNode dc = new DefaultMutableTreeNode("DC"),
                marvel = new DefaultMutableTreeNode("Marvel"), capcom = new DefaultMutableTreeNode("Capcom"), mortal = new DefaultMutableTreeNode("Mortal Kombat");

        for (Personajes per : personajes) {
            DefaultMutableTreeNode nodPer = new DefaultMutableTreeNode(per);
            switch (per.getUniverso()) {
                case "DC": {
                    dc.add(nodPer);
                }
                break;
                case "Marvel": {
                    marvel.add(nodPer);
                }
                break;
                case "Capcom": {
                    capcom.add(nodPer);
                }
                break;
                case "Mortal Kombat": {
                    mortal.add(nodPer);
                }
                break;
            }
        }

        raiz.add(dc);
        raiz.add(marvel);
        raiz.add(capcom);
        raiz.add(mortal);
        DefaultTreeModel m = new DefaultTreeModel(raiz);

        jT_Personajes.setModel(m);

    }

    public DefaultListModel Listar(String universo) {
        DefaultListModel model = new DefaultListModel();
        for (Personajes per : personajes) {
            if (per.getUniverso().equals(universo)) {
                model.addElement(per);
            }
        }
        return model;
    }

    DefaultMutableTreeNode nodSel = new DefaultMutableTreeNode();
    Personajes perSel = new Personajes();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaBattle;
    private javax.swing.JComboBox<String> CB_Jug1;
    private javax.swing.JComboBox<String> CB_Jug2;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JPopupMenu PopMenu;
    private javax.swing.JButton Salida;
    private javax.swing.ButtonGroup bG_Universo;
    private javax.swing.JButton jBT_Fis;
    private javax.swing.JButton jBT_Men;
    private javax.swing.JButton jBT_Res;
    private javax.swing.JButton jB_Battle;
    private javax.swing.JButton jB_Crear2;
    private javax.swing.JButton jB_EVolver;
    private javax.swing.JButton jB_Listar;
    private javax.swing.JButton jB_Regreso;
    private javax.swing.JButton jB_crear1;
    private javax.swing.JFrame jF_Battle;
    private javax.swing.JFrame jF_Crear;
    private javax.swing.JFrame jF_Listar;
    private javax.swing.JList<String> jL_Jug1;
    private javax.swing.JList<String> jL_Jug2;
    private javax.swing.JList<String> jL_Personajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRB_CapCom;
    private javax.swing.JRadioButton jRB_DC;
    private javax.swing.JRadioButton jRB_MK;
    private javax.swing.JRadioButton jRB_Marvel;
    private javax.swing.JSpinner jS_Fisica;
    private javax.swing.JSpinner jS_Fuerza;
    private javax.swing.JSpinner jS_HP;
    private javax.swing.JSpinner jS_Mental;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTF_Debilidad;
    private javax.swing.JTextField jTF_Nombre;
    private javax.swing.JTextField jTF_Poder;
    private javax.swing.JTree jT_Personajes;
    // End of variables declaration//GEN-END:variables
}
